apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: admin-deployment
    spec:
      containers:
      - name: admin-deployment
        image: app/ajax:v3.0
        ports:
        - containerPort: 80
