---
- name: Create DevEnv Instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: Ecommerce_east1
    instance_type: t2.micro
    security_group: devsec
    image: ami-38708b45
    region: us-east-1
  tasks:
    - name: 1.  Launch instance
      ec2:
         aws_access_key: "{{ access }}"
         aws_secret_key: "{{ secret }}"
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
#         count: 1
         instance_tags:
           Name: Ecommerce-DevEnv
         exact_count: 1
         count_tag:
           Name: Ecommerce-DevEnv
         monitoring: no
         region: "{{ region }}"
         assign_public_ip: yes
         vpc_subnet_id: subnet-e2de53a8
      register: ec2
    - name: 2. Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"
    - name: 3.  Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: 4.  assign elastic ip
      ec2_eip:
         aws_access_key: "{{ access }}"
         aws_secret_key: "{{ secret }}"
         device_id: "{{ item }}"
         ip: 18.207.60.86
         region: "{{ region }}"
      with_items: "{{ ec2.instance_ids }}"

