kind: Service
apiVersion: v1
metadata:
  name:  admin-deployment
spec:
  selector:
    application: admin-deployment
    stage: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
